{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-stage
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-stage
  template:
    metadata:
      labels:
        app: mysql-stage
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: {{ .Values.mysql.existingConfigMap }}
            - secretRef:
                name: {{ .Values.mysql.existingSecret }}
          {{- if .Values.mysql.persistence.enabled }}
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql
          {{- end }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
      {{- if .Values.mysql.persistence.enabled }}
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-stage-pvc
      {{- end }}
{{- end }}
