{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-stage-pvc
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
