{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stage
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-stage
  template:
    metadata:
      labels:
        app: redis-stage
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          command: ["redis-server", "--protected-mode", "no"]
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: {{ .Values.redis.existingConfigMap }}
            - secretRef:
                name: {{ .Values.redis.existingSecret }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
