apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./helm

helmCharts:
  - name: springboot-app
    releaseName: springboot-app-stage

# ConfigMap 자동 생성 (Helm Chart에 주입)
configMapGenerator:
  - name: springboot-stage-config
    envs:
      - .env.stage
  - name: prometheus-stage-config
    files:
      - prometheus.yml=./resources/prometheus.stage.yml
  - name: promtail-stage-config
    files:
      - promtail.yaml=./resources/promtail.stage.yml
  - name: grafana-stage-datasource
    files:
      - datasource.yml=./resources/datasource.stage.yml
  - name: grafana-stage-dashboard-provider
    files:
      - dashboards.yml=./resources/dashboard-provider.stage.yml
  - name: grafana-stage-dashboards
    files:
      - dashboard.json=./resources/grafana-dashboard.stage.json

# Secret 자동 생성 (Helm Chart에 주입)
secretGenerator:
  - name: springboot-stage-secret
    envs:
      - .secret.env.stage
