rootProject.name = 'springboot-app'

include 'application'
include 'libs:common-core'
include 'libs:event-core'
include 'libs:event-starter'
include 'libs:jpa-core'
include 'libs:jpa-starter'
include 'libs:logging-core'
include 'libs:logging-starter'
include 'libs:security-core'
include 'libs:security-starter'
include 'libs:web-core'
include 'libs:web-starter'
