plugins {
    id 'java-library'
}

dependencies {
    api project(':libs:common-core')
    implementation 'org.springframework:spring-context'
    
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}