spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:?Missing required environment variable 'SPRING_PROFILES_ACTIVE'.}

  application:
    name: springboot-app
  
  output:
    ansi:
      enabled: always
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: validate

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
