spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:?Missing required environment variable 'SPRING_PROFILES_ACTIVE'. Please check your deployment config.}

  application:
    name: springboot-app
  
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: ${DB_CONN_MINIMUM_IDLE}
      maximum-pool-size: ${DB_CONN_MAXIMUM_POOL_SIZE}
      connection-timeout: ${DB_CONN_CONNECTION_TIMEOUT}
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}

  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}

server:
  shutdown: graceful

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_EXPIRATION}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_EXPIRATION}
