spring:
  application:
    name: springboot-app
  
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL}
        show_sql: ${JPA_SHOW_SQL}

  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT}

server:
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_EXPIRATION}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_LOG_LEVEL}
        type:
          descriptor:
            sql:
              BasicBinder: ${HIBERNATE_LOG_LEVEL}
