{
 "title": "My Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "App Name",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, application)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "log_level", "label": "Log Level", "query": "DEBUG,INFO,WARN,ERROR" },
   {
    "name": "pod_status",
    "label": "Pod Status",
    "query": {
     "query": "label_values(kube_pod_status_phase, phase)"
    }
   },
   {
    "name": "mysql_pod",
    "label": "MySQL Pod",
    "query": {
     "query": "query_result(last_over_time(kube_pod_status_phase{phase=~\"${pod_status}\", pod=~\"mysql-stage.*\"}[1m]) == 1)"
    }
   },
   {
    "name": "app_pod",
    "label": "App Pod",
    "query": {
     "query": "query_result(last_over_time(kube_pod_status_phase{phase=~\"${pod_status}\", pod=~\"springboot-app-stage.*\"}[1m]) == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mysql - Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL CPU Usage vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"mysql\", pod=~\"${mysql_pod}\"}[1m])) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"mysql\", pod=~\"${mysql_pod}\", resource=\"cpu\"}",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"mysql\", pod=~\"${mysql_pod}\"}) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"mysql\", pod=~\"${mysql_pod}\", resource=\"memory\"}",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"mysql\", pod=~\"${mysql_pod}\"}[1m])) by (pod)",
     "legendFormat": "Throttled Time: {{pod}}"
    }
   ]
  },
  { "title": "Springboot - Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Springboot CPU Usage vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"springboot-app\", pod=~\"${app_pod}\"}[1m])) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"springboot-app\", pod=~\"${app_pod}\", resource=\"cpu\"}",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Springboot Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"springboot-app\", pod=~\"${app_pod}\"}) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"springboot-app\", pod=~\"${app_pod}\", resource=\"memory\"}",
     "legendFormat": "Limit: {{pod}}"
    }
   ]
  },
  {
   "title": "Springboot CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"springboot-app\", pod=~\"${app_pod}\"}[1m])) by (pod)",
     "legendFormat": "Throttled Time: {{pod}}"
    }
   ]
  },
  { "title": "Springboot - Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"${app_name}\", area=\"heap\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - Used"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"${app_name}\", area=\"heap\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - Max"
    }
   ]
  },
  {
   "title": "JVM GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"${app_name}\", pod=~\"${app_pod}\"}[1m])",
     "legendFormat": "{{pod}} - GC Pause"
    }
   ]
  },
  {
   "title": "JVM & Tomcat Live Thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"${app_name}\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - JVM Total"
    },
    {
     "expr": "tomcat_threads_current_threads{application=\"${app_name}\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - Tomcat Current"
    },
    {
     "expr": "tomcat_threads_active_threads{application=\"${app_name}\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - Tomcat Active"
    }
   ]
  },
  {
   "title": "JVM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"${app_name}\", pod=~\"${app_pod}\"}",
     "legendFormat": "{{pod}} - CPU"
    }
   ]
  },
  { "title": "Springboot - Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(level) (\n  rate(\n    {app=\"${app_name}\", pod=~\"${app_pod}\"} \n    | json \n    | level =~ \"${log_level}\" \n    |= \"${log_keyword}\" \n    [1m]\n  )\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "{app=\"${app_name}\", pod=~\"${app_pod}\"} | json | level =~ \"${log_level}\" | line_format \"{{.level}} [{{.logger_name}}] {{.message}}\""
    }
   ]
  },
  { "title": "Ingress / Response Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"${app_name}\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"${app_name}\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"${app_name}\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"${app_name}\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"${app_name}\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  sum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) \r\n  or \r\n  sum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", uri!=\"/actuator/prometheus\"}) * 0\r\n) \r\n/ \r\nsum by(uri) (http_server_requests_seconds_count{application=\"${app_name}\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"${app_name}\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=\"${app_name}\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}