package com.example.lib.event.core;

import com.example.lib.common.core.context.trace.TraceContext;
import com.example.lib.common.core.context.trace.TraceContextHolder;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("BaseEvent 테스트")
class BaseEventTest {

    // 테스트용 EventSource
    private static final EventSource TEST_SOURCE = () -> "TEST";

    // 테스트용 EventType
    private static final EventType TEST_TYPE = DefaultEventType.of("TEST_001", "테스트 이벤트");

    // 테스트용 구체 이벤트
    static class TestSystemEvent extends BaseSystemEvent {
        TestSystemEvent(EventType type, EventSource source) {
            super(type, source);
        }
    }

    static class TestDomainEvent extends BaseDomainEvent {
        TestDomainEvent(EventType type, EventSource source) {
            super(type, source);
        }
    }

    @AfterEach
    void tearDown() {
        TraceContextHolder.clearContext();
    }

    @Nested
    @DisplayName("기본 필드 자동 생성")
    class AutoGeneratedFields {

        @Test
        @DisplayName("eventId는 항상 고유한 UUID로 생성된다")
        void eventIdIsUniqueUuid() {
            TestSystemEvent e1 = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);
            TestSystemEvent e2 = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(e1.getEventId()).isNotNull();
            assertThat(e2.getEventId()).isNotNull();
            assertThat(e1.getEventId()).isNotEqualTo(e2.getEventId());
        }

        @Test
        @DisplayName("timestamp는 생성 시점의 시간으로 채워진다")
        void timestampIsSetOnCreation() {
            TestSystemEvent event = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(event.getTimestamp()).isNotNull();
        }

        @Test
        @DisplayName("traceId가 컨텍스트에 있으면 이벤트에 복사된다")
        void traceIdIsCopiedFromContext() {
            TraceContextHolder.setContext(TraceContext.create("trace-xyz"));

            TestSystemEvent event = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(event.getTraceId()).isEqualTo("trace-xyz");
        }

        @Test
        @DisplayName("traceId 컨텍스트가 없으면 null이 설정된다")
        void traceIdIsNullWithoutContext() {
            TestSystemEvent event = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(event.getTraceId()).isNull();
        }
    }

    @Nested
    @DisplayName("EventType / EventSource 바인딩")
    class Binding {

        @Test
        @DisplayName("생성 시 주입된 EventType이 그대로 유지된다")
        void eventTypeIsPreserved() {
            TestSystemEvent event = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(event.getEventType().getCode()).isEqualTo("TEST_001");
            assertThat(event.getEventType().getDescription()).isEqualTo("테스트 이벤트");
        }

        @Test
        @DisplayName("생성 시 주입된 EventSource가 그대로 유지된다")
        void eventSourceIsPreserved() {
            TestSystemEvent event = new TestSystemEvent(TEST_TYPE, TEST_SOURCE);

            assertThat(event.getEventSource().getName()).isEqualTo("TEST");
        }

        @Test
        @DisplayName("BaseDomainEvent도 동일하게 동작한다")
        void domainEventAlsoWorks() {
            EventSource domainSource = () -> "ORDER";
            EventType domainType = DefaultEventType.of("ORDER_001", "주문 완료");

            TestDomainEvent event = new TestDomainEvent(domainType, domainSource);

            assertThat(event.getEventType().getCode()).isEqualTo("ORDER_001");
            assertThat(event.getEventSource().getName()).isEqualTo("ORDER");
        }
    }
}
