apiVersion: v2
name: springboot-app
description: A Helm chart for Spring Boot Application and its dependencies (MySQL, Prometheus, Grafana, Loki, Promtail)
type: application
version: 0.1.0
appVersion: "1.0.0"
