application:
  replicaCount: 1
  image:
    repository: springboot-app
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  
  existingConfigMap: "springboot-stage-config"
  existingSecret: "springboot-stage-secret"

  env: {}
  secrets: {}

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 40

mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
  service:
    port: 3306
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  existingConfigMap: "springboot-stage-config"
  existingSecret: "springboot-stage-secret"

  secrets: {}

ingress:
  enabled: true
  className: "nginx"
  grafana:
    service: grafana-stage
    port: 3000
  prometheus:
    service: prometheus-stage
    port: 9090

monitoring:
  enabled: true
  prometheus:
    existingConfigMap: "prometheus-stage-config"
    image: prom/prometheus:latest
    service:
      type: NodePort
      port: 9090
      nodePort: 30090
  grafana:
    existingDatasourceConfigMap: "grafana-stage-datasource"
    existingDashboardProviderConfigMap: "grafana-stage-dashboard-provider"
    existingDashboardsConfigMap: "grafana-stage-dashboards"
    image: grafana/grafana:11.0.0
    service:
      type: NodePort
      port: 3000
      nodePort: 30000
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: standard

logging:
  enabled: true
  loki:
    image: grafana/loki:2.9.2
    service:
      port: 3100
  promtail:
    existingConfigMap: "promtail-stage-config"
    image: grafana/promtail:2.9.2
