apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-pvc
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
