apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          command: ["redis-server", "--protected-mode", "no"]
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.existingConfigMap }}
            - secretRef:
                name: {{ .Values.global.existingSecret }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
