apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "springboot-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ .Values.application.service.port | quote }}
      labels:
        {{- include "springboot-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv mysql 3306; do echo waiting for mysql; sleep 2; done;"]
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.application.image | quote }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.application.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.global.existingConfigMap }}
            - secretRef:
                name: {{ .Values.global.existingSecret }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms1024m -Xmx1536m"
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
