apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-app.fullname" . }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "springboot-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ .Values.application.service.port | quote }}
      labels:
        {{- include "springboot-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.application.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.application.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.global.existingConfigMap }}
            - secretRef:
                name: {{ .Values.global.existingSecret }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms512m -Xmx768m"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10
